[package]
authors = ["chenyang"]
edition = "2024"
name = "rudis"
version = "0.1.0"

[dependencies]
clap = {version = "4.2.1", features = ["derive"]}
env_logger = "0.8"
log = "0.4"
tokio = {version = "1.47.1", features = ["full"]}
